# Generated by Django 3.2.5 on 2021-09-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0004_alter_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room'),
        ),
    ]
