### start
GET {{HOST}}/{{defaultVersion}}

### all quiz
GET {{HOST}}/{{defaultVersion}}/quiz

### all quiz with optionns
GET {{HOST}}/{{defaultVersion}}/quiz/with-option?search=2

### one quiz
GET {{HOST}}/{{defaultVersion}}/quiz/1

### create Quiz
POST {{HOST}}/{{defaultVersion}}/quiz
Content-Type: application/json

{
  "title": "hello2 quiz",
  "description": "who2 is invent Han-gule"

}

### create Question
POST {{HOST}}/{{defaultVersion}}/question
Content-Type: application/json

{
  "question": "22 here is question for quiz2",
  "quizId": 2
}

### create Optopn
POST {{HOST}}/{{defaultVersion}}/option
Content-Type: application/json

{
  "text": "option for question1",
  "isCorrect": true,
  "questionId": 1
}