### start
GET {{HOST}}/{{defaultVersion}}

### all quiz
GET {{HOST}}/{{defaultVersion}}/quiz

### all quiz with optionns
GET {{HOST}}/{{defaultVersion}}/quiz/with-option?search=2

### one quiz
GET {{HOST}}/{{defaultVersion}}/quiz/1

### one quiz with options
GET {{HOST}}/{{defaultVersion}}/quiz/with-option/2

### create Quiz
POST {{HOST}}/{{defaultVersion}}/quiz
Content-Type: application/json

{
  "title": "Programming Common Sense",
  "description": "Very Easy Common sense for beginners"

}

### create Question
POST {{HOST}}/{{defaultVersion}}/question
Content-Type: application/json

{
  "question": "CREATE for what?",
  "quizId": 2
}

### create Optopn
POST {{HOST}}/{{defaultVersion}}/option
Content-Type: application/json

{
  "text": "make one row data",
  "isCorrect": true,
  "questionId": 7
}