### register
POST {{HOST}}/{{defaultVersion}}/user/register
Content-Type: application/json

{
  "name": "TwoFace",
  "email": "flip@villain.com",
  "password": "2111",
  "confirm": "1211"
}

### login
POST {{HOST}}/{{defaultVersion}}/auth/login
Content-Type: application/json

{
  "email": "flip@villain.com1",
  "password": "2111"
}