spring:
  redis:
    sentinel:
      master: mainRedis
      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
# 그러나 그냥 무설정 상태에서 이렇게는 동작 하지 않는다.
# 네트워크상 센티넬이 가르키는 메인 네트워크가 host에서 바라보는 ip/port가 expose된 네트워크와 다르기 때문
# 실제 서비스에서는 java app 도 compose되어 올라가므로 nodes 에 docker network를 기입하게 될 것이다.
