#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use App\SpeakCommand;

require __DIR__.'/vendor/autoload.php';

$app =  new Application("My Console app", "0.1");

$app->add(new SpeakCommand);
$app->run();

