spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: on
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: facam
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    root: info

server:
  port: 8081

apis:
    product-graphql-api:
      url: http://localhost:8083/graphql
    order-api:
      url: http://localhost:9090/providers/order-api/v1/orders