# default server port
server:
  port: 8080

# Live Reload, Cache setting
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: facam
    driver-class-name: com.mysql.cj.jdbc.Driver
