[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2018"
authors = ["sunday00 <kind65505256@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
