version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
    env_file:
      - ../.env