[package]
name = "sunday00_profiles"
version = "0.1.0"
edition = "2018"
description = "completely practice"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
