### create user register
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
  "username": "sunday00ko",
  "password": "1111"
}

### sign user to get request token
# @name signUser
POST {{baseUrl}}/v1/auth/signin
Content-Type: application/json

{
  "username": "sunday00",
  "password": "1111"
}


# > {% client.global.set('ACCESS_TOKEN', response.body.access_token); %}

### token

@accessToken = {{signUser.response.body.$.access_token}}

### user profile
GET {{baseUrl}}/v1/auth/me
Authorization: Bearer {{accessToken}}

### update password
PATCH {{baseUrl}}/v1/auth/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "sunday00",
  "password": "1111"
}
