### create user register
POST {{HOST}}/v1/auth/register
Content-Type: application/json

{
  "username": "sunday00ko",
  "password": "1111"
}

### sign user
POST {{HOST}}/v1/auth/signin
Content-Type: application/json

{
  "username": "sunday00",
  "password": "1112"
}

> {% client.global.set('ACCESS_TOKEN', response.body.access_token); %}

### user profile
GET {{HOST}}/v1/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}

### update password
PATCH {{HOST}}/v1/auth/1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "sunday00",
  "password": "1111"
}
