### all boards
GET {{HOST}}/board

### create boards
POST {{HOST}}/board
Content-Type: application/json

{
  "title": "test Hawk",
  "description": "Take Off Hawk!"
}

> {% client.global.set('LAST_BOARD_ID', response.body.id); %}

### create null boards
POST {{HOST}}/board
Content-Type: application/json

{
  "title": "",
  "description": ""
}

### get one by id
GET {{HOST}}/board/{{LAST_BOARD_ID}}

### get one 404
GET {{HOST}}/board/abcd

### update status one by id
PATCH  {{HOST}}/board/{{LAST_BOARD_ID}}/status
Content-Type: application/json

{
  "status": "PRIVATE"
}

### delete one by id
DELETE {{HOST}}/board/{{LAST_BOARD_ID}}