### sign user
POST {{HOST}}/v1/auth/signin
Content-Type: application/json

{
  "username": "sunday00",
  "password": "1111"
}

> {% client.global.set('ACCESS_TOKEN', response.body.access_token); %}

### all boards
GET {{HOST}}/v1/board?page=1
Authorization: Bearer {{ACCESS_TOKEN}}

### my boards
GET {{HOST}}/v1/board/mine
Authorization: Bearer {{ACCESS_TOKEN}}

### create boards
POST {{HOST}}/v1/board
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "title": "My Original",
  "description": "Take Off Hawk22!"
}

> {% client.global.set('LAST_BOARD_ID', response.body.id); %}

### create null boards
POST {{HOST}}/board
Content-Type: application/json

{
  "title": "",
  "description": ""
}

### create other type body
POST {{HOST}}/board
Content-Type: application/json

{
  "title": 123,
  "description": false
}


### get one by id
GET {{HOST}}/board/{{LAST_BOARD_ID}}

### get one 404
GET {{HOST}}/board/abcd

### update status one by id
PATCH {{HOST}}/v1/board/3/status
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "PRIVATE"
}

### update status one not correct type
PATCH  {{HOST}}/board/{{LAST_BOARD_ID}}/status
Content-Type: application/json

{
  "status": false
}

### delete one by id
DELETE {{HOST}}/v1/board/9
Authorization: Bearer {{ACCESS_TOKEN}}

### delete 404
DELETE {{HOST}}/board/abcde