# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: cd 012-tdd-nest
    - run: npm install
      uses: actions/setup-node@v3
      working-directory: 012-tdd-nest
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm test
      working-directory: 012-tdd-nest
